name: 'jsonnetfmt'
description: 'Run jsonnetfmt to check if jsonnet files are formatted in current workspace'
branding:
  icon: 'feather'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
